In [123]:
import numpy as np
from calculations.circle_calculations import calc_size_circle

In [14]:
# aanmaken numpy array
numbers_list = [1,2,3,4,5]
numbers_array = np.array(numbers_list)

In [15]:
numbers_list + numbers_list

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [16]:
numbers_array + numbers_array

array([ 2,  4,  6,  8, 10])

In [5]:
numbers_list / numbers_list

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [6]:
numbers_array / numbers_array

array([1., 1., 1., 1., 1.])

In [7]:
numbers_array * 10

array([10, 20, 30, 40, 50])

In [9]:
numbers_list * 10

'ArieArieArieArieArieArieArieArieArieArie'

In [10]:
numbers_array.max()

5

In [11]:
numbers_array.sum()

15

In [17]:
numbers_array_2 = np.array([3,4,5,6,7])

In [18]:
numbers_array.sum()

15

In [19]:
numbers_array_2.sum()

25

In [21]:
# meerdere arrays optellen
np.sum([numbers_array, numbers_array_2])

40

In [ ]:
np.array([1,2,3,4,5])

In [22]:
# arrays aanmakenm
numbers_array_1 = np.array([10, 16, 8, 3, 44])
numbers_array_2 = np.array([6, 20, 15, 1, 63])

In [23]:
# arrays van elkaar aftrekken om de verschillen te zien (met negatieven)
numbers_array_1 - numbers_array_2

array([  4,  -4,  -7,   2, -19])

In [24]:
# de absolute verschillen tussen de arrays
np.abs(numbers_array_1 - numbers_array_2)

array([ 4,  4,  7,  2, 19])

In [25]:
# list concatenaten
numbers_list + numbers_list

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [26]:
# gaat fout met + voor arrays
numbers_array_1 + numbers_array_2

array([ 16,  36,  23,   4, 107])

In [28]:
# np.concatenate gebruiken --> Let op de vierkante haakjes
np.concatenate([numbers_array_1, numbers_array_2, numbers_array_2])

array([10, 16,  8,  3, 44,  6, 20, 15,  1, 63,  6, 20, 15,  1, 63])

In [29]:
numbers_array_combined = np.concatenate([numbers_array_1, numbers_array_2])

# Selectie

In [31]:
numbers_array_combined[0]

10

In [32]:
numbers_array_combined

array([10, 16,  8,  3, 44,  6, 20, 15,  1, 63])

In [34]:
numbers_array_combined[-4:]

array([20, 15,  1, 63])

In [35]:
naam = "Arie"

In [36]:
naam[2]

'i'

In [37]:
naam[-3:]

'rie'

In [39]:
numbers_array_combined[1, 5]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [41]:
np.take(numbers_array_combined, [1, 5])

array([16,  6])

In [42]:
numbers_array_1

array([10, 16,  8,  3, 44])

In [43]:
numbers_array_2

array([ 6, 20, 15,  1, 63])

In [44]:
d2_numbers_array = np.array([numbers_array_1, numbers_array_2])

In [45]:
d2_numbers_array

array([[10, 16,  8,  3, 44],
       [ 6, 20, 15,  1, 63]])

In [50]:
d2_numbers_array[1, 2]

15

In [63]:
numbers_array_3 = np.array([[[1,2],[1,2],[1,2],[1,2], [1,2]], [[1,2],[1,2],[1,2],[1,2], [1,2]]])

In [68]:
numbers_array_3

array([[[1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2]],

       [[1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2]]])

In [69]:
numbers_array_3[0]

array([[1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2]])

In [70]:
numbers_array_3[0][4]

array([1, 2])

In [71]:
numbers_array_3[0][4][1]

2

In [73]:
numbers_array_3[0, 4, 1]

2

# Filtering

In [77]:
numbers_array_combined


array([10, 16,  8,  3, 44,  6, 20, 15,  1, 63])

In [75]:
numbers_array_combined > 10

array([False,  True, False, False,  True, False,  True,  True, False,
        True])

In [83]:
numbers_array_combined[numbers_array_combined > 10]

array([16, 44, 20, 15, 63])

In [84]:
type(numbers_array_combined)

numpy.ndarray

In [86]:
# conditional statements
ages_array = np.array([15, 21, 30, 45, 17, 11, 45, 30, 21, 15])
ages_array

array([15, 21, 30, 45, 17, 11, 45, 30, 21, 15])

In [87]:
ages_array > 21

array([False, False,  True,  True, False, False,  True,  True, False,
       False])

In [94]:
ages_adult_array = np.where(ages_array > 21, "Adult", "Non-adult")
ages_adult_array

array(['Non-adult', 'Non-adult', 'Adult', 'Adult', 'Non-adult',
       'Non-adult', 'Adult', 'Adult', 'Non-adult', 'Non-adult'],
      dtype='<U9')

In [90]:
# datatypen in lists an arrays
info_list = [1, "Arie", True, 1.94]

In [91]:
info_array = np.array(info_list)

In [92]:
info_array

array(['1', 'Arie', 'True', '1.94'], dtype='<U32')

In [96]:
# show the unique values
np.unique(ages_adult_array)

array(['Adult', 'Non-adult'], dtype='<U9')

In [97]:
# show unique values and occurences
np.unique(ages_adult_array, return_counts=True)

(array(['Adult', 'Non-adult'], dtype='<U9'), array([4, 6]))

# Assignments

In [98]:
# assignemnt 1
# Create 3 Numpy arrays from the following three lists:

array_1 = [20, 56]
array_2 = [11, 78]
array_3 = [43, 65]

In [103]:
# assignment 7- Create a function, split_odd_even that accepts 
# a numpy array and returns the odd and even numbers in two seperate arrays.


diameters = np.concatenate([array_1, array_2, array_3])
diameters

array([20, 56, 11, 78, 43, 65])

In [124]:
# calculate the size of the circle

calc_size_circle(40)

1256.6370614359173

In [122]:
from typing import Tuple

# apply the funct
def split_odd_even(input_array: np.ndarray) -> Tuple[np.ndarray[int], np.ndarray[int]]:
    '''
    Method to split a numpy array into a odd and even array:

    Output:

    * first array contains the odd numbers
    * second array contains the even numbers
    
    '''
    odd_numbers = input_array[input_array % 2 == 1]
    even_numbers = input_array[input_array % 2 == 0]

    return odd_numbers, even_numbers

In [121]:
# applly the function to the 'diameters' array
odd_diameters, even_diameters = split_odd_even(diameters)

In [117]:
# apply to the sizes

array([20, 56, 78])